# Generated by Django 4.2.2 on 2023-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsallocated',
            name='remaining_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
