# Generated by Django 4.1.7 on 2023-04-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanUsertransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=255)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=255)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_transactions', to='loan.loan')),
                ('repayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loan.loanrepayment')),
            ],
        ),
    ]
