# Generated by Django 4.2.2 on 2023-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_transaction_options_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='start_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='month',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
