# Generated by Django 4.2.2 on 2023-06-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loan_start_month_loanrepayment_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
